#!/usr/bin/env python3
"""
Resolution Applier for 16S Census Parser
=========================================

Applies AI-resolved taxonomic resolutions back to the CSV output files.
Updates unmapped taxa (NA) with their resolved lineages.

This module reads the CSV files generated by the initial taxonkit pass,
applies resolutions from the AI resolver, and writes updated CSV files.
"""

import csv
import logging
from pathlib import Path
from typing import Dict

logger = logging.getLogger(__name__)


def apply_resolutions_to_csv(
    csv_file: Path,
    resolutions: Dict[str, Dict],
    rank: str,
    total_otu_count: int,
    total_size_count: int
) -> int:
    """
    Apply resolutions to a CSV file by updating NA entries.
    
    Args:
        csv_file: Path to the CSV file to update
        resolutions: Dictionary of resolutions from the AI resolver
        rank: Taxonomic rank (phylum, family, or genus)
        total_otu_count: Total OTU count for percentage calculations
        total_size_count: Total size count for percentage calculations
    
    Returns:
        Number of resolutions applied
    """
    if not csv_file.exists():
        logger.warning(f"CSV file not found: {csv_file}")
        return 0
    
    # Read the CSV file
    rows = []
    header = None
    
    with open(csv_file, 'r') as f:
        reader = csv.reader(f)
        header = next(reader)
        rows = list(reader)
    
    logger.info(f"Read {len(rows)} rows from {csv_file.name}")
    
    # Apply resolutions
    applied_count = 0
    
    for i, row in enumerate(rows):
        # CSV format: name, taxid, otu_count, otu_percentage, size_count, size_percentage, lineage, lineage_ranks, lineage_taxids
        if len(row) < 9:
            continue
        
        name = row[0]
        taxid = row[1]
        
        # Only update if taxid is NA and we have a resolution
        if taxid == "NA" and name in resolutions:
            resolution = resolutions[name]
            
            # Update the row with resolved information
            rows[i][1] = resolution['parent_taxid']  # taxid
            rows[i][6] = resolution['lineage']  # lineage
            rows[i][7] = resolution['lineage_ranks']  # lineage_ranks
            rows[i][8] = resolution['lineage_taxids']  # lineage_taxids
            
            applied_count += 1
            logger.info(f"  ✅ Applied resolution: {name} → {resolution['parent_name']}")
    
    # Write updated CSV
    with open(csv_file, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(header)
        writer.writerows(rows)
    
    logger.info(f"Applied {applied_count} resolutions to {csv_file.name}")
    return applied_count


def update_unmapped_log(
    log_file: Path,
    resolutions: Dict[str, Dict]
):
    """
    Update the unmapped log to remove resolved taxa.
    
    Args:
        log_file: Path to the unmapped log file
        resolutions: Dictionary of resolutions from the AI resolver
    """
    if not log_file.exists():
        logger.warning(f"Unmapped log not found: {log_file}")
        return
    
    # Read the log file
    with open(log_file, 'r') as f:
        lines = f.readlines()
    
    # Filter out resolved taxa
    filtered_lines = []
    removed_count = 0
    
    for line in lines:
        # Keep header lines and summary lines
        if line.startswith('#') or line.startswith('===') or line.strip() == '':
            filtered_lines.append(line)
            continue
        
        # Check if this line contains a resolved taxon
        is_resolved = False
        for taxon_name in resolutions.keys():
            if f"| {taxon_name} |" in line or line.startswith(f"PHYLUM | {taxon_name}") or line.startswith(f"FAMILY | {taxon_name}") or line.startswith(f"GENUS | {taxon_name}"):
                is_resolved = True
                removed_count += 1
                break
        
        if not is_resolved:
            filtered_lines.append(line)
    
    # Write updated log
    with open(log_file, 'w') as f:
        f.writelines(filtered_lines)
    
    logger.info(f"Removed {removed_count} resolved taxa from unmapped log")


def apply_all_resolutions(
    csv_output_dir: Path,
    log_dir: Path,
    resolutions_by_rank: Dict[str, Dict[str, Dict]],
    output_prefix: str,
    total_otu_count: int,
    total_size_count: int
) -> Dict[str, int]:
    """
    Apply all resolutions to CSV files and update unmapped log.
    
    Args:
        csv_output_dir: Directory containing CSV output files
        log_dir: Directory containing log files
        resolutions_by_rank: Dictionary mapping rank to resolutions
        output_prefix: Prefix for output files
        total_otu_count: Total OTU count for percentage calculations
        total_size_count: Total size count for percentage calculations
    
    Returns:
        Dictionary with counts of applied resolutions per rank
    """
    logger.info("\n" + "="*80)
    logger.info("APPLYING RESOLUTIONS TO CSV FILES")
    logger.info("="*80)
    
    applied_counts = {}
    
    # Apply resolutions for each rank
    for rank, resolutions in resolutions_by_rank.items():
        if not resolutions:
            logger.info(f"\nNo resolutions to apply for {rank}")
            continue
        
        logger.info(f"\n[{rank.upper()}] Applying {len(resolutions)} resolutions...")
        
        # Determine CSV file name based on rank
        if rank == "phylum":
            csv_file = csv_output_dir / f"{output_prefix}_by_division.csv"
        elif rank == "family":
            csv_file = csv_output_dir / f"{output_prefix}_by_family.csv"
        elif rank == "genus":
            csv_file = csv_output_dir / f"{output_prefix}_by_genus.csv"
        else:
            logger.warning(f"Unknown rank: {rank}")
            continue
        
        # Apply resolutions
        count = apply_resolutions_to_csv(
            csv_file, resolutions, rank,
            total_otu_count, total_size_count
        )
        applied_counts[rank] = count
    
    # Update unmapped log
    logger.info("\nUpdating unmapped log...")
    all_resolutions = {}
    for resolutions in resolutions_by_rank.values():
        all_resolutions.update(resolutions)
    
    unmapped_log = log_dir / f"{output_prefix}_comprehensive_unmapped.log"
    update_unmapped_log(unmapped_log, all_resolutions)
    
    logger.info("\n" + "="*80)
    logger.info("RESOLUTION APPLICATION COMPLETE")
    logger.info("="*80)
    for rank, count in applied_counts.items():
        logger.info(f"  {rank}: {count} resolutions applied")
    
    return applied_counts

