#!/usr/bin/env python3
"""
Resolution Applier for Systematic Family Resolver

Applies systematic resolutions to CSV files generated by the taxonkit parser.
"""

import csv
import json
import logging
from pathlib import Path
from typing import Dict


def load_resolutions(resolution_file: Path) -> Dict[str, Dict]:
    """
    Load systematic resolutions from JSON file.
    
    Args:
        resolution_file: Path to resolutions JSON file
        
    Returns:
        Dictionary mapping family names to resolution information
    """
    if not resolution_file.exists():
        logging.error(f"Resolution file not found: {resolution_file}")
        return {}
    
    with open(resolution_file, 'r') as f:
        resolutions = json.load(f)
    
    logging.info(f"Loaded {len(resolutions)} systematic resolutions")
    return resolutions


def apply_resolutions_to_csv(
    input_csv: Path,
    output_csv: Path,
    resolutions: Dict[str, Dict],
    level_name: str
) -> int:
    """
    Apply systematic resolutions to a CSV file.
    
    Args:
        input_csv: Path to input CSV file (from taxonkit parser)
        output_csv: Path to output CSV file (with resolutions applied)
        resolutions: Dictionary of systematic resolutions
        level_name: Name of the taxonomic level (for logging)
        
    Returns:
        Number of entries that were resolved
    """
    if not input_csv.exists():
        logging.error(f"Input CSV not found: {input_csv}")
        return 0
    
    logging.info(f"Applying resolutions to {level_name} CSV...")
    
    resolved_count = 0
    total_count = 0
    
    # Read input CSV and apply resolutions
    rows = []
    with open(input_csv, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            total_count += 1
            name = row['Name_to_use']
            
            # Check if this name has a systematic resolution
            if name in resolutions:
                resolution = resolutions[name]
                
                # Update lineage fields with resolved values
                row['lineage'] = resolution['lineage']
                row['lineage_ranks'] = resolution['lineage_ranks']
                row['lineage_taxids'] = resolution['lineage_taxids']
                
                resolved_count += 1
                logging.debug(f"Applied resolution for {name}")
            
            rows.append(row)
    
    # Write output CSV
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_csv, 'w', newline='') as f:
        if rows:
            fieldnames = rows[0].keys()
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)
    
    logging.info(f"Applied {resolved_count}/{total_count} resolutions to {level_name}")
    logging.info(f"Output written to {output_csv}")
    
    return resolved_count


def create_final_unmapped_log(
    original_unmapped_log: Path,
    resolutions: Dict[str, Dict],
    output_log: Path
):
    """
    Create final unmapped log showing only taxa that are still unmapped
    after systematic resolution.

    Args:
        original_unmapped_log: Path to original unmapped log from taxonkit parser
        resolutions: Dictionary of systematic resolutions
        output_log: Path to output log file
    """
    if not original_unmapped_log.exists():
        logging.error(f"Original unmapped log not found: {original_unmapped_log}")
        return

    logging.info("Creating final unmapped log (post-resolution)...")

    resolved_taxa = set(resolutions.keys())
    still_unmapped_families = []
    still_unmapped_genera = []

    # Read original log and filter out resolved taxa
    with open(original_unmapped_log, 'r') as f:
        lines = f.readlines()

    # First pass: collect unmapped taxa by filtering out resolved ones
    family_section_lines = []
    genus_section_lines = []
    header_lines = []
    in_family_section = False
    in_genus_section = False
    family_count_line_idx = None
    genus_count_line_idx = None

    for line in lines:
        if line.startswith('=== FAMILY LEVEL UNMAPPED NAMES ==='):
            in_family_section = True
            in_genus_section = False
            family_section_lines.append(line)
            continue

        if line.startswith('=== GENUS LEVEL UNMAPPED NAMES ==='):
            in_family_section = False
            in_genus_section = True
            genus_section_lines.append(line)
            continue

        if in_family_section:
            if line.startswith('FAMILY |'):
                parts = line.split('|')
                if len(parts) >= 2:
                    taxon_name = parts[1].strip()
                    if taxon_name not in resolved_taxa:
                        family_section_lines.append(line)
                        still_unmapped_families.append(taxon_name)
            elif line.startswith('==='):
                # End of family section
                in_family_section = False
                family_section_lines.append(line)
            elif line.startswith('Total unmapped'):
                # Save position to update count later
                family_count_line_idx = len(family_section_lines)
                family_section_lines.append(line)  # Placeholder
            else:
                family_section_lines.append(line)
        elif in_genus_section:
            if line.startswith('GENUS |'):
                parts = line.split('|')
                if len(parts) >= 2:
                    taxon_name = parts[1].strip()
                    if taxon_name not in resolved_taxa:
                        genus_section_lines.append(line)
                        still_unmapped_genera.append(taxon_name)
            elif line.startswith('==='):
                # End of genus section
                in_genus_section = False
                genus_section_lines.append(line)
            elif line.startswith('Total unmapped'):
                # Save position to update count later
                genus_count_line_idx = len(genus_section_lines)
                genus_section_lines.append(line)  # Placeholder
            else:
                genus_section_lines.append(line)
        else:
            header_lines.append(line)

    # Update count lines
    if family_count_line_idx is not None:
        family_section_lines[family_count_line_idx] = f"Total unmapped family entries: {len(still_unmapped_families)}\n"
    if genus_count_line_idx is not None:
        genus_section_lines[genus_count_line_idx] = f"Total unmapped genus entries: {len(still_unmapped_genera)}\n"

    # Combine all sections
    output_lines = header_lines + family_section_lines + genus_section_lines

    # Write final log
    output_log.parent.mkdir(parents=True, exist_ok=True)

    with open(output_log, 'w') as f:
        f.write("# Final Unmapped Taxa Log (POST-RESOLUTION)\n")
        f.write(f"# Systematic resolutions applied: {len(resolved_taxa)}\n")
        f.write(f"# Families still unmapped: {len(still_unmapped_families)}\n")
        f.write(f"# Genera still unmapped: {len(still_unmapped_genera)}\n\n")
        f.writelines(output_lines)

    logging.info(f"Final unmapped log written to {output_log}")
    logging.info(f"Resolved {len(resolved_taxa)} taxa ({len(still_unmapped_families)} families + {len(still_unmapped_genera)} genera still unmapped)")

